# Generated by Django 3.1.7 on 2021-03-20 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('eid', models.AutoField(db_column='eid', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('iid', models.AutoField(db_column='iid', primary_key=True, serialize=False)),
                ('index_name', models.TextField(unique=True)),
                ('ticker', models.TextField(unique=True)),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('base_divisor', models.DecimalField(decimal_places=4, default=100, max_digits=15)),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.AutoField(db_column='pid', primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('telephone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('folio_id', models.AutoField(db_column='folio_id', primary_key=True, serialize=False)),
                ('pname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sid', models.AutoField(db_column='sid', primary_key=True, serialize=False)),
                ('ticker', models.TextField(unique=True)),
                ('total_stocks', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wish_id', models.AutoField(db_column='wish_id', primary_key=True, serialize=False)),
                ('wname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('bid', models.OneToOneField(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='market.person')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('username', models.TextField(unique=True)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clid', models.OneToOneField(db_column='clid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='market.person')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('username', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.OneToOneField(db_column='cid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='market.stock')),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(default='https://logo.clearbit.com/clearbit.com')),
                ('zipcode', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('industry', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockWishlist',
            fields=[
                ('stock_wish_id', models.AutoField(db_column='stock_wish_id', primary_key=True, serialize=False)),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
                ('wish_id', models.ForeignKey(db_column='wish_id', on_delete=django.db.models.deletion.DO_NOTHING, to='market.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('stock_price_id', models.AutoField(db_column='stock_price_id', primary_key=True, serialize=False)),
                ('creation_time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.exchange')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
            ],
            options={
                'get_latest_by': 'creation_time',
            },
        ),
        migrations.CreateModel(
            name='Stocklists',
            fields=[
                ('last_price_id', models.AutoField(db_column='last_price_id', primary_key=True, serialize=False)),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.exchange')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredAt',
            fields=[
                ('reg_id', models.AutoField(db_column='reg_id', primary_key=True, serialize=False)),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('rec_id', models.AutoField(db_column='rec_id', primary_key=True, serialize=False)),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfIndex',
            fields=[
                ('partof_id', models.AutoField(db_column='partof_id', primary_key=True, serialize=False)),
                ('iid', models.ForeignKey(db_column='iid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.indices')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='OldOrder',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creation_time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('order_type', models.TextField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')])),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.exchange')),
                ('folio_id', models.ForeignKey(db_column='folio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='market.portfolio')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='ListedAt',
            fields=[
                ('listed_id', models.AutoField(db_column='listed_id', primary_key=True, serialize=False)),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.exchange')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPriceHistory',
            fields=[
                ('index_price_id', models.AutoField(db_column='index_price_id', primary_key=True, serialize=False)),
                ('creation_time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iid', models.ForeignKey(db_column='iid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.indices')),
            ],
            options={
                'get_latest_by': 'creation_time',
            },
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('hold_id', models.AutoField(db_column='hold_id', primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('folio_id', models.ForeignKey(db_column='folio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='market.portfolio')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='BuySellOrder',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('completed_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creation_time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('order_type', models.TextField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')])),
                ('eid', models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.exchange')),
                ('folio_id', models.ForeignKey(db_column='folio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='market.portfolio')),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_number', models.BigIntegerField(db_column='account_number', primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pid', models.ForeignKey(db_column='pid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='market.person')),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='clid',
            field=models.ForeignKey(db_column='clid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.client'),
        ),
        migrations.AddConstraint(
            model_name='stockwishlist',
            constraint=models.UniqueConstraint(fields=('wish_id', 'sid'), name='wish_stock_pkey'),
        ),
        migrations.AddConstraint(
            model_name='stockpricehistory',
            constraint=models.UniqueConstraint(fields=('sid', 'eid', 'creation_time', 'price'), name='stock_price_pkey'),
        ),
        migrations.AddConstraint(
            model_name='stocklists',
            constraint=models.UniqueConstraint(fields=('sid', 'eid'), name='stock_exchange_price_pkey'),
        ),
        migrations.AddField(
            model_name='registeredat',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.broker'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.broker'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='clid',
            field=models.ForeignKey(db_column='clid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.client'),
        ),
        migrations.AddConstraint(
            model_name='partofindex',
            constraint=models.UniqueConstraint(fields=('sid', 'iid'), name='stock_index_pkey'),
        ),
        migrations.AddField(
            model_name='oldorder',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.broker'),
        ),
        migrations.AddConstraint(
            model_name='listedat',
            constraint=models.UniqueConstraint(fields=('sid', 'eid'), name='exchange_stock_pkey'),
        ),
        migrations.AddConstraint(
            model_name='indices',
            constraint=models.UniqueConstraint(fields=('eid', 'index_name'), name='unique_index_exchange'),
        ),
        migrations.AddConstraint(
            model_name='indexpricehistory',
            constraint=models.UniqueConstraint(fields=('iid', 'creation_time', 'price'), name='index_price_pkey'),
        ),
        migrations.AddConstraint(
            model_name='holdings',
            constraint=models.UniqueConstraint(fields=('folio_id', 'sid'), name='portfolio_stock_pkey'),
        ),
        migrations.AddField(
            model_name='buysellorder',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.broker'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(check=models.Q(balance__gte=0), name='valid_balance'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('clid', 'wname'), name='client_wishlist_pkey'),
        ),
        migrations.AddConstraint(
            model_name='registeredat',
            constraint=models.UniqueConstraint(fields=('bid', 'eid'), name='broker_exchange_reg_pkey'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('bid', 'sid'), name='broker_stock_recommend_pkey'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('clid', 'pname'), name='client_portfolio_pkey'),
        ),
        migrations.AddConstraint(
            model_name='buysellorder',
            constraint=models.CheckConstraint(check=models.Q(completed_quantity__lte=django.db.models.expressions.F('quantity')), name='valid_buy_state_check'),
        ),
    ]
