# Generated by Django 3.1.7 on 2021-03-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='holding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='client',
            name='holding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
