# Generated by Django 3.1.7 on 2021-03-14 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partofindex',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='clid',
            field=models.ForeignKey(db_column='clid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.client'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.broker'),
        ),
        migrations.AlterField(
            model_name='registeredat',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.broker'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='clid',
            field=models.ForeignKey(db_column='clid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.client'),
        ),
    ]
