# Generated by Django 3.0.1 on 2021-03-17 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buysellorder',
            old_name='initial_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='oldorder',
            name='reg_id',
        ),
        migrations.AddField(
            model_name='buysellorder',
            name='order_type',
            field=models.TextField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oldorder',
            name='bid',
            field=models.ForeignKey(db_column='bid', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='market.Broker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oldorder',
            name='eid',
            field=models.ForeignKey(db_column='eid', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='market.Exchange'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oldorder',
            name='order_type',
            field=models.TextField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy'),
            preserve_default=False,
        ),
    ]
