# Generated by Django 3.1.7 on 2021-03-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210314_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='latency',
        ),
        migrations.AlterField(
            model_name='broker',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
