# Generated by Django 3.1.7 on 2021-04-03 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import timescale.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20210321_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creation_time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('order_type', models.TextField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')])),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='buysellorder',
            name='valid_buy_state_check',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='holding_balance',
        ),
        migrations.AddField(
            model_name='broker',
            name='latency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='buysellorder',
            constraint=models.CheckConstraint(check=models.Q(completed_quantity__lte=django.db.models.expressions.F('quantity')), name='valid_buysell_state_check'),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.broker'),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='eid',
            field=models.ForeignKey(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.exchange'),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='folio_id',
            field=models.ForeignKey(db_column='folio_id', on_delete=django.db.models.deletion.DO_NOTHING, to='market.portfolio'),
        ),
        migrations.AddField(
            model_name='pendingorder',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='market.stock'),
        ),
    ]
