# Generated by Django 2.2.6 on 2021-03-10 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField()),
                ('index_name', models.TextField(blank=True, null=True)),
                ('eid', models.OneToOneField(db_column='eid', on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('telephone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registeredat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.ForeignKey(db_column='eid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('total_stocks', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.OneToOneField(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sm.Person')),
                ('commission', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('latency', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sm.Person')),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stockwishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.TextField()),
                ('clid', models.OneToOneField(db_column='clid', on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Wishlist')),
                ('ticker', models.ForeignKey(db_column='ticker', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Sellorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('pname', models.TextField(blank=True, null=True)),
                ('eid', models.IntegerField(blank=True, null=True)),
                ('initial_quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('completed_quantity', models.IntegerField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(blank=True, db_column='bid', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Registeredat')),
                ('clid', models.ForeignKey(blank=True, db_column='clid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Portfolio')),
                ('ticker', models.ForeignKey(blank=True, db_column='ticker', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Pricehistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('eid', models.ForeignKey(db_column='eid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Exchange')),
                ('ticker', models.OneToOneField(db_column='ticker', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Partof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.IntegerField()),
                ('eid', models.ForeignKey(db_column='eid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Indices')),
                ('ticker', models.OneToOneField(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Oldorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('pname', models.TextField(blank=True, null=True)),
                ('eid', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('order_type', models.TextField()),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(blank=True, db_column='bid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Registeredat')),
                ('clid', models.ForeignKey(blank=True, db_column='clid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Portfolio')),
                ('ticker', models.ForeignKey(blank=True, db_column='ticker', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Listedat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.ForeignKey(db_column='eid', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Exchange')),
                ('ticker', models.OneToOneField(db_column='ticker', on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ticker', models.ForeignKey(blank=True, db_column='ticker', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Buyorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('pname', models.TextField(blank=True, null=True)),
                ('eid', models.IntegerField(blank=True, null=True)),
                ('initial_quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('completed_quantity', models.IntegerField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(blank=True, db_column='bid', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Registeredat')),
                ('clid', models.ForeignKey(blank=True, db_column='clid', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Portfolio')),
                ('ticker', models.ForeignKey(blank=True, db_column='ticker', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='clid',
            field=models.OneToOneField(db_column='clid', on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Client'),
        ),
        migrations.AddField(
            model_name='registeredat',
            name='bid',
            field=models.OneToOneField(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Broker'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.ForeignKey(db_column='ticker', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Stock')),
                ('bid', models.OneToOneField(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Broker')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='clid',
            field=models.OneToOneField(db_column='clid', on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Client'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=5, max_digits=10)),
                ('clid', models.ForeignKey(blank=True, db_column='clid', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sm.Client')),
            ],
        ),
    ]
